"""
Django settings for tagging_tracker project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

if DEBUG:
    SECRET_KEY = 'mysecretkey'
else:
    # NEVER put the secret key in a settings file. Always set it as an env variable in your .zshrc/.bashrc file.
    SECRET_KEY = os.environ['SECRET_KEY']

ALLOWED_HOSTS = ['52.173.204.52', 'localhost', '127.0.0.1', '0.0.0.0', 'tagtracker.centralus.cloudapp.azure.com']

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'tagtracking',
        'USER': 'tagfighter@taggingtracker',
        'HOST': 'taggingtracker.postgres.database.azure.com',
        'PORT': '5432',
        'PASSWORD': os.environ['DB_PW'],
    }
}

